@echo off
md "01 JS Tutorial"
md "02 JS Versions"
md "03 JS Objects"
md "04 JS Functions"
md "05 JS Classes"
md "06 JS Async"
md "07 JS HTML DOM"
md "08 JS Browser BOM"
md "09 JS Web APIs"
md "10 JS AJAX"
md "11 JS JSON"
md "12 JS vs jQuery"
md "13 JS Graphics"
md "14 JS Examples"
md "15 JS References"