@echo off
md "01 JSON Intro"
md "02 JSON Syntax"
md "03 JSON vs XML"
md "04 JSON Data Types"
md "05 JSON Parse"
md "06 JSON Stringify"
md "07 JSON Objects"
md "08 JSON Arrays"
md "09 JSON Server"
md "10 JSON PHP"
md "11 JSON HTML"
md "12 JSON JSONP"